enum ACTIONS {
  CHANGE_KEYWORD = "CHANGE_KEYWORD",
  CHANGE_SERVICE = "CHANGE_SERVICE",
  CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION",
  SET_IS_PAID = "SET_IS_PAID",
  DAY_LIMIT = "DAY_LIMIT",
  DELETE_KEYWORD = "DELETE_KEYWORD",
  DAY_LIMIT_NUMBER = "DAY_LIMIT_NUMBER",
  CLEAR_DATA = "CLEAR_DATA"
};
export default ACTIONS;