enum ACTIONS {
  CHANGE_KEYWORD = "CHANGE_KEYWORD",
  CHANGE_SERVICE = "CHANGE_SERVICE",
  CHANGE_TITLE = "CHANGE_TITLE",
  CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION",
  DELETE_SERVICE = "DELETE_SERVICE"
};
export default ACTIONS;